### ISSUE TITLE
Karten-Massstab hinzufügen

### ISSUE THREAD

**Issue by Hannes-Ole** [HAFL-WWI/Digital-Forest-Monitoring#103]
Der Kartenviewer könnte noch einen Massstab (m / km) gebrauchen. Es kam eine Rückmeldung eines Nutzers, dass er das gerne hätte.
Eher niedrige Priorität.

**Comment by hkfrei** [comment]
Ist eingebaut.

**Comment by Hannes-Ole** [comment]
tested on Mobile und Desktop 👍
