### ISSUE TITLE
MapViewer Performance (Post CrowdSourcing)

### ISSUE THREAD

**Issue by Hannes-Ole** [HAFL-WWI/Digital-Forest-Monitoring#105]
Wie in #104 bereits diskutiert, gibt es immer wieder auftretende Probleme mit der Performance (lange Ladezeiten, einzelne tiles werden gar nicht geladen.

Damit verbunden hat @hkfrei Optimierungen vorgenommen:

> Kapazität des Geoservers nochmals erhöht.
> Zudem habe ich die Rasterdaten präpariert. Sie sind nun optimal mit Overviews und InnerTiling versehen. Sie waren es eigentlich schon, aber ich hab noch ein paar Overviews hinzugefügt.

Ist nun alles WMTS? (-> close #104)

Eine weitere Baustelle ist seit dem Crowdsourcing Element der WFS Layer:
> Ein grosses Problem ist momentan der WFS fürs Crowdsourcing. Es werden immer alle Features welche sich im Kartenausschnitt befinden geladen. Wenn viele Layer an sind und der Kartenausschnitt gross ist, sind das hunderttausende von Features. 

M.E. ist das Laden ab einer bestimmten Zoomstufe eine sehr gute Idee! (ungefähr die unten abgebildete Zoomstufe denke ich reicht völlig aus)
Damit verbunden sollte #103 der Karten-Massstab hinzugefügt werden und ausserdem ein Hinweis Text an irgendeiner Stelle eingefügt werden, so dass der Nutzer weiss, er kann erst ab 1:2000 oder Skala = 1 km (o.ä.) beginnen, die Features zu editieren. Eine "Dokumentation/Tutorial" für das Crowdsourcing steht ohnehin noch aus, diesbzgl. werde ich demnächst etwas liefern.

![grafik](https://user-images.githubusercontent.com/72789281/179468059-5b03e190-a871-456b-8aee-f8c7e07a55d3.png)

**Comment by hkfrei** [comment]
Im Moment läuft immer noch der WMS in der WebApplikation. Ich denke wir sollten diesen auch performant bereitstellen, deshalb möchte ich erst auf WMTS umstellen, sobald der WMS gut läuft und dies lässt sich auf waldmonitoring.ch sehr gut testen.
Alles klar, die WFS Sachen und die Massstabsleiste werde ich so umsetzen. 👍.
