### ISSUE TITLE
Info Crowdsourcing / Zoomstufe

### ISSUE THREAD

**Issue by Hannes-Ole** [HAFL-WWI/Digital-Forest-Monitoring#106]
Es braucht noch ein Tutorial/Info (Button? Hinweis-Pop-Up?), um auf das interaktive Crowdsourcing Element (validieren der Features) hinzuweisen. Werde mir etwas überlegen.
Bei der Gelegenheit können wir auch darauf hinweisen, dass erst ab Zoomstufe 15 das editieren der Daten möglich ist.

Nachricht von Hanskaspar (06.02.2023):
Ich habe in meiner Entwicklungsumgebung die Nachricht bezüglich der Zoomstufen/Crowdsourcing probehalber implementiert. Soweit ich weiss, lieferst du mir noch den Text dazu. Habe ich das richtig im Kopf?

**Comment by Hannes-Ole** [comment]
@hkfrei Hier endlich text für ein Info-Pop-Up. Laut deiner Nachricht vom 6.2 hast du ja bereits einen Template für das Info-Popup fertig :) sorry, dass es so lange gedauert hat:

DE:

Die jährlichen Veränderungsdaten sind kalibriert mit den Rückmeldungen von Menschen, die ihren Wald gut kennen (Crowdsourcing). Kennen Sie eine Veränderungsfläche? Sind Flächen nicht plausibel oder falsch? Geben Sie direkt im Viewer Rückmeldung:
Veränderungsflächen können ab Zoomstufe 15 (Massstab wechselt zu 200m) angewählt werden für Rückmeldungen.

Ihre Rückmeldung hilft uns, die Daten kontinuierlich zu verbessern. Vielen Dank dafür!


FR:

Les données annuelles sur les changements sont calibrées avec les réactions des personnes qui connaissent bien leur forêt (crowdsourcing). Connaissez-vous une surface de changement ? Les surfaces ne sont pas plausibles ou sont fausses ? Donnez votre avis directement dans la visionneuse :
Les surfaces de changement peuvent être sélectionnées à partir du niveau de zoom 15 (l'échelle passe à 200 m) pour obtenir des informations.

Votre feed-back nous aide à améliorer continuellement les données. Nous vous en remercions !

EN:

Annual change data is calibrated with feedback from people who know their forest well (crowdsourcing). Do you know an area of change? Are areas not plausible or wrong? Give feedback directly in the viewer:
Change areas can be selected from zoom level 15 (scale changes to 200m) for feedback.

Your feedback helps us to continuously improve the data. Thank you very much!

**Comment by hkfrei** [comment]
@Hannes-Ole 
Super, danke für den Text. Ich habe ihn jetzt beim UC1 eingebaut. Im Template habe ich noch einen Titel definiert gehabt. Diesen habe ich vorerst so belassen wie er war.  Wenn er dich, stört bitte ungeniert melden ;-)
EN haben wir bisher nicht in den Translations. Deshalb habe ich einfach DE und FR übernommen. Man könnte EN schon hinzufügen, aber dann müsste man die Übersetzung für alle Elemente erfassen -> https://docs.google.com/spreadsheets/d/1ouSogLBySSER3bi8pEuHVdi3-ODx-K1GzYSIp57EmmU/edit#gid=0

**Comment by Hannes-Ole** [comment]
Perfekt, danke dir. Ja, mal sehen ob ich irgendwann noch Englisch mache oder jemand bei uns Zeit hat. Für jetzt schliesse ich diesen Issue.
