### ISSUE TITLE
Mehrsprachigkeit

### ISSUE THREAD

**Issue by Hannes-Ole** [HAFL-WWI/Digital-Forest-Monitoring#107]
Für den Gebrauch im französisch-sprachigen Raum wird in naher Zukunft eine übersetzte Version benötigt.
Wie besprochen macht es Sinn, an dieser Stelle über ein Frame-Work-"Wechsel" nachzudenken und allenfalls grundsätzlichere Änderungen vor zu nehmen.

**Comment by hkfrei** [comment]
Ja genau. Wichtig ist insbesondere, dass man die requirements welche das System in Zukunft erfüllen soll definiert (User Management, Mehrsprachigkeit, Backend, Daten editieren, 3D etc.). Auch sollte man sich überlegen, wo man die Applikationsgrenze zieht. Die Erfahrung zeigt, dass es keinen Sinn macht einen Monolithen zu bauen der alles kann. Oft werden diese Applikationen mit der Zeit langsam und sind schwer zu unterhalten. Besser sind mehrere (kleine) Applikationen mit ganz gezieltem Einsatzgebiet. Diese können Beispielsweise über eine Landingpage verfügbar gemacht werden. Somit muss der User nur eine Adresse kennen.
