### ISSUE TITLE
Schwellwert-Aktualisierung UC1 / neue Styles

### ISSUE THREAD

**Issue by Hannes-Ole** [HAFL-WWI/Digital-Forest-Monitoring#109]
Die neuen Daten (2015/16 und 2021/22) sind online mit einem geupdateten SLD.
Der Geoserver scheint anders als QGIS die Werte ausserhalb des definierten Gradienten standardmässig zu clippen (in QGIS ist das eine Extra-Option, die aber nicht ins SLD übertragen werden kann, das habe ich getestet). Damit die Flächen <-0.4 auch dargestellt werden, müssen wir den Schwellwert auf das Maximum setzen (zur Sicherheit -10'000).
Ich werde die Styles entsprechend anpassen und überlege noch, wie ich es am sinnvollsten mache (ich will nicht, dass die Farben bis -10'000 interpoliert werden, dadurch verlieren sie zuviel Kontrast; vermutlich läuft es auf ein zusätzliches Legenden-Item hinaus).

Hier ein Beispiel aus dem Viewer:
![grafik](https://user-images.githubusercontent.com/72789281/198305737-4f788318-8968-4bad-9c00-8a891ace3cbc.png)

im Vergleich die Fläche in QGIS mit demselben Style:
![grafik](https://user-images.githubusercontent.com/72789281/198305757-86a2b252-5f47-4f36-82c5-ecbd3cccd6c2.png)

**Comment by Hannes-Ole** [comment]
Zudem noch ein Detail: Die "Farb-Range" hat sich erweitert (um den Kontrast zu erhöhen), damit sind die "Maximalwerte" dunkler. Das "deep saffron" (orange) wirkt dadurch eher braun. Die Legendenitems sollten am besten den "Basis-Farbton" zeigen (die Hex-Codes dafür sind [hier](https://github.com/HAFL-WWI/Digital-Forest-Monitoring/issues/100#issuecomment-940890019) ):
```
/* OVERVIEW RAINBOW 1 - 7 */
--cg-red: #eb3333
--deep-saffron: #f3942c
--yellow-pantone: #f8e025
--mantis: #80c757
--medium-turquoise: #46d8d5
--iris: #4545d9
--dark-orchid: #a444d6
```
![grafik](https://user-images.githubusercontent.com/72789281/198315325-872a713a-45b3-4a25-9b1c-d7ee1de48a3a.png)

**Comment by hkfrei** [comment]
Alles klar, ich hab das angepasst.

**Comment by Hannes-Ole** [comment]
![grafik](https://user-images.githubusercontent.com/72789281/198328763-bc7f2abc-1bbe-43df-a9f5-7d8dbabf41ba.png)
