### ISSUE TITLE
Test Banner entfernen für UC1 (und UC3)

### ISSUE THREAD

**Issue by Hannes-Ole** [HAFL-WWI/Digital-Forest-Monitoring#113]
Aktuell ist das Test Banner noch für die ganze Seite. Wir sollten es dort entfernen und jeweils per einzelnen Use Cases machen (auf die Kacheln): UC2 und UC4.

**Comment by hkfrei** [comment]
Der Test Banner ist jetzt von der Hauptseite entfernt und bei den Kacheln von UC2 und UC4 hinzugefügt.
Frage: Reicht es auf den Kacheln, oder muss der Banner auch erscheinen wenn man den UC2 oder 4 Viewer öffnet?

**Comment by Hannes-Ole** [comment]
Perfekt, habe es gerade gesehen. Das reicht auf jeden Fall so. 
Wenn es keine fixe Grafik ist, kannst du ihn gern noch etwas grösser machen und dafür aber grau oder blau. So können wir einen roten Banner an Kacheln machen die wir Neu hinzufügen ;)

**Comment by hkfrei** [comment]
Welche Version findest du am besten?
![image](https://github.com/HAFL-WWI/Digital-Forest-Monitoring/assets/6850977/de9798c9-95a8-488d-9bb2-438601eb46aa)

![image](https://github.com/HAFL-WWI/Digital-Forest-Monitoring/assets/6850977/fd62cae9-d2e3-4f17-99c2-0a7227a9aebb)

![image](https://github.com/HAFL-WWI/Digital-Forest-Monitoring/assets/6850977/34933e78-aa7f-44e9-9533-83560c420ec1)


![image](https://github.com/HAFL-WWI/Digital-Forest-Monitoring/assets/6850977/ab9fc133-184e-47b6-8779-145d9e102151)

**Comment by Hannes-Ole** [comment]
Danke @hkfrei, ich bin 100% einverstanden mit gelb 👍
