### ISSUE TITLE
Google Analytics für waldmonitoring.ch

### ISSUE THREAD

**Issue by Hannes-Ole** [HAFL-WWI/Digital-Forest-Monitoring#114]
Für google analytics benötigen:
- einen Code Snippet, den @Hannes-Ole generiert
- ein Abfragedialog bzgl. Datenschutz/Cookies

**Comment by Hannes-Ole** [comment]
@hkfrei 
ich habe soeben folgenden Tag installiert. Ich hoffe, ich habe alles richtig gemacht... beim Dialog zu "properties" (gefragt war ein Name, Zeitzone, Währung) war ich mir nicht sicher. Ich habe das "property" nun einfach mal "property_1" genannt. K.A. ob relevant.
Den Tag habe ich für die Domain waldmonitoring.ch erstellt.
```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-N04HYQE9LL"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-N04HYQE9LL');
</script>
```

**Comment by hkfrei** [comment]
@Hannes-Ole 
Das  Snippet ist jetzt eingebunden und entsprechend sollte man den Traffic jetzt auf dem Dashboard von Google Analyics sehen.

**Comment by hkfrei** [comment]
@Hannes-Ole 
Ich habe noch am Cookie Disclaimer gearbeitet. Diesen brauchen wir wegen Google Analytics. Folgende Fragen sind noch aufgetaucht:
-  Wie sollen die Texte für DE und FR lauten (Ein einfacher Vorschlag findest du im Bild unten)?
-  Habt ihr eine Datenschutzerklärung?
-  Durch Klick auf den OK Button könnte man die Einstellung für das jeweilige Gerät speichern und beim nächsten Aufruf den Disclaimer nicht mehr anzeigen (wenn ihr das möchtet).
![image](https://github.com/HAFL-WWI/Digital-Forest-Monitoring/assets/6850977/a499fa67-38d3-4b68-976e-57825618301c)

**Comment by Hannes-Ole** [comment]
Sehr schön umgesetzt, das ist eine vorbildliche Implementierung, die den Gebrauch der Homepage nicht beeinträchtigt 👍 
Den Text finde ich auch gut; eine Datenschutzerklärung haben wir nicht.
Ich habe noch ergänzt, dass wir die Cookies nur zur Messung des Besuchsaufkommens nutzen. Die Übersetzung ist einfach aus DeepL. Gerne kannst du das wording ändern, wenn du es umständlich findest (und ggf. automatisch übersetzen ;) )

- waldmonitoring.ch verwendet Cookies für eine Statistik zur Anzahl der Aufrufe der Homepage. Durch die Nutzung stimmen Sie der Verwendung von Cookies zu. 

- waldmonitoring.ch utilise des cookies pour établir des statistiques sur le nombre de visites de la page d'accueil. En l'utilisant, vous acceptez l'utilisation de cookies.

**Comment by hkfrei** [comment]
@Hannes-Ole 
Die Texte sind jetzt angepasst. Ich habe sie genau wie oben übernommen.
