### ISSUE TITLE
Webviewer lädt erst bei zweitem Aufruf

### ISSUE THREAD

**Issue by Hannes-Ole** [HAFL-WWI/Digital-Forest-Monitoring#116]
Aktuell (ich glaube seit dem Hinweis zu den Cookies) ist es bei mir so, dass beim Öffnen von https://waldmonitoring.ch die Seite nur halb lädt (ohne Kacheln/Webviewer) und nur beim zweiten Aufruf komplett:
![grafik](https://github.com/HAFL-WWI/Digital-Forest-Monitoring/assets/72789281/575b6a98-5c6b-47bc-9dbe-78281ce76f0e)

Ich nutze Firefox 118.0.1 (64-Bit)

**Comment by hkfrei** [comment]
@Hannes-Ole 
Ich habe den "production bundler" auf die neuste version aktualisiert und ein neues production bundle erstellt und auf den Webserver hochgeladen. Kannst du nochmals probieren? 
Hast du eine Fehlermeldung in der Browser Konsole wenn der Fehler auftritt?

**Comment by Hannes-Ole** [comment]
Aktuell kann ich den Fehler nicht mehr reproduzieren, also ein vorsichtiges "Jau, funktioniert nun" :) wenn es nochmal auftritt melde ich mich hier! Danke dir für die prompte Reaktion 👍
