### ISSUE TITLE
Kartenviewer: Legende VHM

### ISSUE THREAD

**Issue by Hannes-Ole** [HAFL-WWI/Digital-Forest-Monitoring#96]
Das VHM hat als Basemap leider keine Legende (Mail vom 16.9). Hanskaspar: "Man könnte aber beispielsweise neben dem Text «VHM» ein (i) platzieren, welches auf Klick die Layerinfos darstellt."
Das wäre eine gute Lösung.

**Comment by hkfrei** [comment]
Ist nun umgesetzt. Es hat nicht viel Platz fürs (i) aber es funktioniert ;-)  Die Legende und das Abstract werden direkt vom Swisstopo WMS abgefragt, deshalb dauert es etwas länger als bei den anderen Layerinfos.
![image](https://user-images.githubusercontent.com/6850977/143458936-49af2e7b-ac8a-4feb-a3f2-24a54ff132b0.png)

**Comment by Hannes-Ole** [comment]
Tiptop, den Platz perfekt genutzt. Gefällt mir gut 👍 danke für die Umsetzung
